x-global-envs:
  &global-envs
    HOST: "0.0.0.0"
    PORT: 80
    DRONES_NUMBER: 3

services:
    drone-1:
        container_name: drone-1
        build:
            context: .
            dockerfile: "Dockerfile"
        environment:
            <<: *global-envs
            BEHAVIOR: leader
            INITIAL_POS_X: 1
            INITIAL_POS_Y: 2
        networks:
            app_network:
                ipv4_address: 192.168.100.10
        ports:
            - "80:80"
        stdin_open: true
        tty: true

    drone-2:
        container_name: drone-2
        build:
            context: .
            dockerfile: "Dockerfile"
        environment:
            <<: *global-envs
            BEHAVIOR: on-mission
        networks:
            app_network:
                ipv4_address: 192.168.100.11
        ports:
            - "81:80"
        stdin_open: true
        tty: true

    drone-3:
        container_name: drone-3
        build:
            context: .
            dockerfile: "Dockerfile"
        environment:
            <<: *global-envs
            BEHAVIOR: on-mission
        networks:
            app_network:
                ipv4_address: 192.168.100.12
        ports:
            - "82:80"
        stdin_open: true
        tty: true

networks:
    app_network:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.100.0/24
